version: '3'

services:
  node:
    image: node:14
    build: .
    working_dir: /app
    volumes:
      - ".:/app"
    ports:
      - "8081:3000"
    links:
      - mongo
    command: ["yarn", "start"]
    environment:
      - URL_MONGO=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME}
      - BASE_URL=${BASE_URL}
      - NODE_ENV=${NODE_ENV}
      - OG_BASE_URL=${OG_BASE_URL}
      - KERING_APP_TOKEN=${KERING_APP_TOKEN}
      - KERING_OG_ID=${KERING_OG_ID}

  mongo:
    image: mongo:4.0
    volumes:
      - "./mongo/data:/data/db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
