version: '3'

services:
  node:
    build: .
    volumes:
      - ".:/app"
    ports:
      - "8081:3000"
    links:
      - mongo
    command: bash -c "cd /app && yarn build-dev && ./node_modules/.bin/pm2 start startup.json --name API --no-daemon"
    environment:
      - URL_MONGO=mongodb://api:docker1234@mongo

  mongo:
    image: mongo:4.0
    volumes:
      - "./mongo/data:/data/db"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=api
      - MONGO_INITDB_ROOT_PASSWORD=docker1234
